### ISSUE TITLE
Nest tags missing 2019 season

### ISSUE THREAD

**Issue by RyanDou** [dbca-wa/wastd#330]
There are no nest tag observations that have been imported into WAStD from the 2019/2020 season (except those from Port Hedland who I assume were using the UAT form).

## Reproducible example
I have no idea the steps that led to this bug however...
This url is a nest encounter where an excavation was undertaken: https://wastd.dbca.wa.gov.au/admin/observations/encounter/160085/change/?_changelist_filters=when__day%3D30%26when__month%3D1%26when__year%3D2020
If you look at the photo associated with the encounter you can see that the nest tag for that encounter was JG8. Using odata I can see that there is a nest tag observation in ODK central that is associated with this encounter (
![image](https://user-images.githubusercontent.com/11881636/91822047-cf306d00-ec69-11ea-8723-5df1ba4b6690.png) however if you go to the nest tag observations in 2020 you can see that this observation is not present: https://wastd.dbca.wa.gov.au/admin/observations/nesttagobservation/?encounter__when__year=2020

**Comment by florianm** [comment]
The ETL script discards all Null records (else it would generate lots of "empty" non-observations). I suspect that this one record could have had a photo, but no text data in the nest tag section. Re-running import now to diagnose.

**Comment by florianm** [comment]
The bug lies with wastd, not wastdr.

`wastd.observations.api.ObservationBatchUpsertViewSet` got "what to update" wrong (contained "to create" records) and failed silently on not updating non-existing records. 
Currently fixed by doing a more manual `update_or_create` instead of the `bulk_update`, but should really fix the `records_to_update` list comprehension which requires a good night's sleep and some serious coffee.

**Comment by florianm** [comment]
Deployed to PROD and data reloaded. https://wastd.dbca.wa.gov.au/admin/observations/encounter/160085/change/?_changelist_filters=when__day%3D30%26when__month%3D1%26when__year%3D2020 for example now shows a TurtleNestTag Observation.
